trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  kubernetesEnvironment: $(KUBERNETES_ENVIRONMENT)
  kubernetesNamespace: $(KUBERNETES_NAMESPACE)
  system.debug: true

stages:
  - stage: Delete
    displayName: Delete Data Ingestion
    jobs:
      - deployment: Delete
        displayName: Delete Data Ingestion Portal Deployment
        environment: $(kubernetesEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmDeploy@0
                  displayName: Helm uninstall Data Ingestion Portal
                  inputs:
                    namespace: $(kubernetesNamespace)
                    command: uninstall
                    arguments: ingestion-portal

                - task: Kubernetes@1
                  displayName: Delete resources in namespace
                  inputs:
                    command: delete
                    arguments: all --all
                    namespace: $(kubernetesNamespace)

                - task: Kubernetes@1
                  displayName: Delete PVCs in namespace
                  continueOnError: true
                  inputs:
                    command: delete
                    arguments: pvc --all
                    namespace: $(kubernetesNamespace)
