trigger:
  branches:
    include:
      - staging

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: templates/variables.yaml

stages:
  - stage: BuildAndPush
    displayName: Build and push Ingestion Portal image
    jobs:
      - template: templates/build-and-push.yaml

  - stage: CreateConfig
    displayName: Create/update K8s configuration resources
    dependsOn: [ ]
    jobs:
      - template: templates/create-config.yaml

  - stage: Deploy
    displayName: Deploy Data Ingestion
    dependsOn:
      - BuildAndPush
      - CreateConfig
    jobs:
      - template: templates/deploy.yaml
