trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  containerRegistryServiceConnection: uniappsoigiga
  kubernetesServiceConnection: $(KUBERNETES_SERVICE_CONNECTION)
  kubernetesNamespace: $(KUBERNETES_NAMESPACE)
  ingestionPortalImageRepository: $(INGESTION_PORTAL_IMAGE_REPOSITORY)
  system.debug: true

steps:
  - task: Bash@3
    displayName: Get short commit hash
    inputs:
      targetType: inline
      script: "SHORT_SHA=`git rev-parse --short HEAD`"
      workingDirectory: $(Build.SourcesDirectory)

  - task: Docker@2
    displayName: Login to container Registry
    inputs:
      command: login
      containerRegistry: $(containerRegistryServiceConnection)

  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: buildAndPush
      repository: giga-data-ingestion
      dockerfile: $(Build.SourcesDirectory)/Dockerfile.prod
      containerRegistry: $(containerRegistryServiceConnection)
      tags: |
        $(Build.SourceVersion)

  - task: HelmDeploy@0
    displayName: Helm deploy Dagster core
    inputs:
      connectionType: Kubernetes Service Connection
      kubernetesServiceEndpoint: $(kubernetesServiceConnection)
      command: upgrade
      chartType: FilePath
      chartPath: infra/helm/data-ingestion
      releaseName: ingestion-portal
      namespace: $(kubernetesNamespace)
      arguments: |
        --values infra/helm/values.yaml \
        --set image.repository="$(containerRegistryServiceConnection).azurecr.io" \
        --set image.tag=$SHORT_SHA
