apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: giga-data-ingestion
  title: Giga Data Ingestion Portal
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: unicef/giga-data-ingestion
  links:
    - url: https://github.com/unicef/giga-data-ingestion
      title: GitHub
  tags:
    - web-app
    - data-ingestion
    - python
    - fastapi
    - typescript
    - react
    - tailwind
    - docker
    - kubernetes
    - helm
spec:
  type: client
  lifecycle: development
  owner: user:tm-kenneth-domingo
