jobs:
  - deployment: Deploy
    displayName: Data Ingestion Portal Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: Docker@2
              displayName: Login to container Registry
              inputs:
                command: login
                containerRegistry: $(ACR_SERVICE_CONNECTION)

            - task: Docker@2
              displayName: Build and push image to container registry
              inputs:
                command: buildAndPush
                repository: giga-ingestion-portal
                dockerfile: $(Build.SourcesDirectory)/Dockerfile.prod
                containerRegistry: $(ACR_SERVICE_CONNECTION)
                tags: |
                  $(Build.SourceVersion)
