jobs:
  - deployment: Deploy
    displayName: Data Ingestion Portal Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Bitnami Helm repo
              inputs:
                command: repo
                arguments: add bitnami https://charts.bitnami.com/bitnami
                namespace: $(kubernetesNamespace)

            - task: HelmDeploy@0
              displayName: Helm deploy PostgreSQL dev
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/postgresql
                chartVersion: 14.0.5
                releaseName: postgres
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/pg-values.yaml
                arguments: >
                  --set architecture=standalone
                  --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy PostgreSQL stg/prd
              condition: or(eq(variables.environment, 'stg'), eq(variables.environment, 'prd'))
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/postgresql
                chartVersion: 14.0.5
                releaseName: postgres
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/pg-values.yaml
                arguments: --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm uninstall Redis
              inputs:
                namespace: $(kubernetesNamespace)
                command: uninstall
                arguments: redis --ignore-not-found

            - task: HelmDeploy@0
              displayName: Helm deploy Redis dev
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/redis
                chartVersion: 18.18.0
                releaseName: redis
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/redis-values.yaml
                arguments: >
                  --set architecture=standalone
                  --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Redis stg/prd
              condition: or(eq(variables.environment, 'stg'), eq(variables.environment, 'prd'))
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/redis
                chartVersion: 18.18.0
                releaseName: redis
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/redis-values.yaml
                arguments: --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy email service dev
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/email-service"
                releaseName: email-service
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal-email"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy email service stg
              condition: eq(variables.environment, 'stg')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/email-service"
                releaseName: email-service
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --values infra/helm/data-ingestion.values-override-prd.yaml
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal-email"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set envFrom[1].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy email service prd
              condition: eq(variables.environment, 'prd')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/email-service"
                releaseName: email-service
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --values infra/helm/data-ingestion.values-override-prd.yaml
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal-email"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Ingestion Portal dev
              condition: eq(variables.environment, 'dev')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/data-ingestion"
                releaseName: ingestion-portal
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="$(ingressHost)"
                  --set ingress.hosts[0].paths[0].path="/"
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set envFrom[1].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Ingestion Portal stg
              condition: eq(variables.environment, 'stg')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/data-ingestion"
                releaseName: ingestion-portal
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --values infra/helm/data-ingestion.values-override-prd.yaml
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="$(ingressHost)"
                  --set ingress.hosts[0].paths[0].path="/"
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set envFrom[1].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Ingestion Portal prd
              condition: eq(variables.environment, 'prd')
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/data-ingestion"
                releaseName: ingestion-portal
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                arguments: >
                  --values infra/helm/data-ingestion.values-override-prd.yaml
                  --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                  --set image.tag="$(deployEnv)-$(Build.SourceVersion)"
                  --set ingress.enabled=true
                  --set ingress.hosts[0].host="$(ingressHost)"
                  --set ingress.hosts[0].paths[0].path="/"
                  --set ingress.hosts[0].paths[0].pathType=Prefix
                  --set ingress.annotations."appgw\.ingress\.kubernetes\.io/appgw-ssl-certificate"=kv-cert-gigaglobal
                  --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                  --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
