jobs:
  - deployment: Deploy
    displayName: Data Ingestion Portal Deployment
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self

            - task: HelmDeploy@0
              displayName: Add Bitnami Helm repo
              inputs:
                command: repo
                arguments: add bitnami https://charts.bitnami.com/bitnami
                namespace: $(kubernetesNamespace)

            - task: HelmDeploy@0
              displayName: Helm deploy PostgreSQL
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/postgresql
                chartVersion: 14.0.5
                releaseName: postgres
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/pg-values.yaml
                ${{ if eq(variables['deployEnv'], 'dev') }}:
                  arguments: --set architecture=standalone

            - task: HelmDeploy@0
              displayName: Helm deploy Redis
              inputs:
                command: upgrade
                chartType: Name
                chartName: bitnami/redis
                chartVersion: 18.18.0
                releaseName: postgres
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/redis-values.yaml
                ${{ if eq(variables['deployEnv'], 'dev') }}:
                  arguments: >
                    --set architecture=standalone
                    --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"
                ${{ else }}:
                  arguments: --set auth.existingSecret="giga-ingestion-portal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy email service
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/email-service"
                releaseName: email-service
                namespace: $(kubernetesNamespace)
                ${{ if or(eq(variables['deployEnv'], 'stg'), eq(variables['deployEnv'], 'prd')) }}:
                  arguments: >
                    --values infra/helm/email-service.values-override.yaml
                    --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal-email"
                    --set image.tag="$(Build.SourceVersion)"
                    --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                    --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
                ${{ else }}:
                  arguments: >
                    --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal-email"
                    --set image.tag="$(Build.SourceVersion)"
                    --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                    --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"

            - task: HelmDeploy@0
              displayName: Helm deploy Ingestion Portal
              inputs:
                command: upgrade
                chartType: FilePath
                chartPath: "$(Build.SourcesDirectory)/infra/helm/data-ingestion"
                releaseName: ingestion-portal
                namespace: $(kubernetesNamespace)
                valueFile: infra/helm/data-ingestion.values-override.yaml
                ${{ if or(eq(variables['deployEnv'], 'stg'), eq(variables['deployEnv'], 'prd')) }}:
                  arguments: >
                    --values infra/helm/data-ingestion.values-override-prd.yaml
                    --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                    --set image.tag="$(Build.SourceVersion)"
                    --set ingress.enabled=true
                    --set ingress.hosts[0].host="io-dataingestion-$(deployEnv).unitst.org"
                    --set ingress.hosts[0].paths[0].path="/"
                    --set ingress.hosts[0].paths[0].pathType=Prefix
                    --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                    --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
                ${{ else }}:
                  arguments: >
                    --set image.repository="$(containerRegistryName).azurecr.io/giga-ingestion-portal"
                    --set image.tag="$(Build.SourceVersion)"
                    --set ingress.enabled=true
                    --set ingress.hosts[0].host="io-dataingestion-$(deployEnv).unitst.org"
                    --set ingress.hosts[0].paths[0].path="/"
                    --set ingress.hosts[0].paths[0].pathType=Prefix
                    --set envFrom[1].secretRef.name="giga-ingestion-portal-secrets-$(deployEnv)"
                    --set envFrom[2].secretRef.name="oi-ingestionportal-secrets-$(deployEnv)"
